apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - git@github.com:gpt-next/base-deploy-repo.git/argocd-image-updater/base?ref=0.1.0-argocd-image-updater
