kind: Secret
apiVersion: v1
metadata:
  name: runner-config-secret
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
data:
  REPO: <github-runner-repo | base64encode>
  TOKEN: <argocd-github-password | base64encode>
type: Opaque
