apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
  labels:
    istio-injection: false
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
       - name: github-runner
         image: ghcr.io/gpt-next/custom-images-github-runner:main
         imagePullPolicy: Always
         envFrom:
         - secretRef:
            name: runner-config-secret
         volumeMounts:
          - name: varlibcontainers
            mountPath: /var/lib/containers
      volumes:
      - name: varlibcontainers
        emptyDir: {}