apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-runner

resources:
  - github.com/gpt-next/base-deploy-repo//github-runner/base?ref=0.2.0-github-runner
  - docker-pull-secret.yaml
  - config-secret.yaml
