apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-monorepo-deploy
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: test=ghcr.io/gpt-next/monorepo/test:~1.0, test2=ghcr.io/gpt-next/monorepo/test2:~1.0
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-update-secret
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/test.update-strategy: latest
    argocd-image-updater.argoproj.io/test.allow-tags: regexp:^v1.0.0-rc[0-9]+$

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: environments
  source:
    repoURL: https://github.com/gpt-next/monorepo-deploy.git
    targetRevision: release/1.0
    path: overlays/qa
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
