apiVersion: v1
kind: Secret
metadata:
  name: argocd-github
  namespace: argocd
  labels:
    "app.kubernetes.io/part-of": "argocd"
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
data:
  clientSecret: <argocd-github-clientSecret | base64encode>
  username: <argocd-github-username | base64encode>
  password: <argocd-github-password | base64encode>
type: Opaque