---
apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
stringData:
  AVP_TYPE: <AVP_TYPE>
  AWS_REGION: <AWS_REGION>
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
type: Opaque
