apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/gpt-next/base-deploy-repo//argocd/base?ref=0.1.0-argocd
  - cluster-level-apps.yaml
  - environments.yaml
  - argocd-github-secret.yaml
  - avp-configuration-secret.yaml
  - crd-argocd.yaml
  - ingress.yaml
  - ../cluster-level-apps
