apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  annotations:
    avp.kubernetes.io/path: "nonprod-secret"
  labels:
    app.kubernetes.io/name: argocd-image-updater-secret
    app.kubernetes.io/part-of: argocd-image-updater
type: Opaque
data:
  argocd.token: <argocd-image-updater-token | base64encode>
