kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: docker-pull-secret
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
data:
  .dockerconfigjson: <docker-pull-secret>
