apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- statefulset.yaml
- service.yaml
- vcs-secret.yaml
- docker-pull-secret.yaml

configMapGenerator:
- name: atlantis-config
  files:
  - repos.yaml
  options:
      disableNameSuffixHash: true
- name: extra-env-vars
  literals:
  - ATLANTIS_REPO_ALLOWLIST=github.com/gpt-next/nonprod-deploy-repo
  - ATLANTIS_GH_HOSTNAME=github.com
  - ATLANTIS_GH_ORG=gpt-next
  - ATLANTIS_ATLANTIS_URL=https://sloth-beloved-wren.ngrok-free.app
  options:
      disableNameSuffixHash: true