---
apiVersion: v1
kind: Secret
metadata:
  name: atlantis-vcs
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
type: Opaque
data:
  atlantis-gh-app-id: <atlantis-gh-app-id>
  atlantis-webhook-secret: <atlantis-webhook-secret>
  gh-app-key-file.pem: <atlantis-gh-app-key-file>
  #atlantis-infracost-api-key: <atlantis-infracost-api-key | base64encode>
  #atlantis-infracost-gh-token: <atlantis-infracost-gh-token | base64encode>