---
apiVersion: v1
kind: Secret
metadata:
  name: atlantis-vcs
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
type: Opaque
data:
  atlantis-gh-app-id: <atlantis-gh-app-id>
  atlantis-webhook-secret: <atlantis-webhook-secret>
  gh-app-key-file.pem: <atlantis-gh-app-key-file>
  atlantis-infracost-api-key: <atlantis-infracost-api-key>
  atlantis-infracost-gh-token: <atlantis-infracost-gh-token | base64encode>
  AWS_ACCESS_KEY_ID: <ATLANTIS_AWS_ACCESS_KEY | base64encode>
  AWS_SECRET_ACCESS_KEY: <ATLANTIS_AWS_SECRET_ACCESS_KEY | base64encode>