apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-monorepo-deploy
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: test=ghcr.io/gpt-next/monorepo/test:latest, test2=ghcr.io/gpt-next/monorepo/test2:latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-update-secret
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/allow-tags: regexp:\b[0-9a-fA-F]{40}\b

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: environments
  source:
    repoURL: https://github.com/gpt-next/monorepo-deploy.git
    targetRevision: main
    path: overlays/dev
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
